sudo: required
services:
  - docker

before_install:
  - docker build -t avincze73/react-test -f ./client/Dockerfile.dev ./client/Dockerfile.dev

script:
  - docker run avincze73/react-test npm test -- --coverage

after_success:
  - docker build -t avincze73/multi-client ./client
  - docker build -t avincze73/multi-nginx ./nginx
  - docker build -t avincze73/multi-server ./server
  - docker build -t avincze73/multi-worker ./worker
  - 
