sudo: required
services:
  - docker

before_install:
  - docker build -t avincze73/react-test -f ./client/Dockerfile.dev ./client/Dockerfile.dev

script:
  - docker run avincze73/react-test npm test -- --coverage

after_success:
  - docker build -t avincze73/complex-client ./client
  - docker build -t avincze73/complex-nginx ./nginx
  - docker build -t avincze73/complex-server ./server
  - docker build -t avincze73/complex-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push avincze73/complex-client
  - docker push avincze73/complex-nginx
  - docker push avincze73/complex-server
  - docker push avincze73/complex-worker